sonar.projectKey=jaiveerraman_email-tone-fixer
sonar.organization=jaiveerraman
sonar.projectName=AI Email Tone Fixer
sonar.projectVersion=1.0

sonar.sources=agents,core,services,api,main.py,config.py
sonar.tests=eval
sonar.exclusions=**/__pycache__/**,**/*.pyc,.venv/**,node_modules/**,*.json,*.lock,*.yaml,*.yml

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
